      new t2dImageMapDatablock(imageMoleRed) {
      canSaveDynamicFields = "1";
      imageName = "./MoleArt/images/molered";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "0";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "9";
      cellCountY = "1";
      cellWidth = "56";
      cellHeight = "98";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(imageMoleLilac) {
      canSaveDynamicFields = "1";
      imageName = "./MoleArt/images/molelilac";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "0";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "9";
      cellCountY = "1";
      cellWidth = "56";
      cellHeight = "98";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(imageMoleGreen) {
      canSaveDynamicFields = "1";
      imageName = "./MoleArt/images/molegreen";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "0";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "9";
      cellCountY = "1";
      cellWidth = "56";
      cellHeight = "98";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(animMoleComeOutRed) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleRed";
      animationFrames = "0 1 2 3 4 4 3";
      animationTime = "0.3";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleDiveInRed) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleRed";
      animationFrames = "4 4 3 2 1 0";
      animationTime = "0.3";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleComeOutLilac) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleLilac";
      animationFrames = "0 1 2 3 4 4 3";
      animationTime = "0.25";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleDiveInLilac) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleLilac";
      animationFrames = "4 4 3 2 1 0";
      animationTime = "0.3";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleComeOutGreen) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleGreen";
      animationFrames = "0 1 2 3 4 4 3";
      animationTime = "0.3";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleDiveInGreen) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleGreen";
      animationFrames = "4 3 2 1 0";
      animationTime = "0.3";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dImageMapDatablock(imageMoleHole) {
      canSaveDynamicFields = "1";
      imageName = "./MoleArt/images/molehole";
      imageMode = "FULL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "0";
      preferPerf = "0";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "-1";
      cellCountY = "-1";
      cellWidth = "0";
      cellHeight = "0";
      preload = "1";
      allowUnload = "0";
   };
   new t2dImageMapDatablock(imageHammer) {
      canSaveDynamicFields = "1";
      imageName = "./MoleArt/images/molehammer";
      imageMode = "CELL";
      frameCount = "-1";
      filterMode = "SMOOTH";
      filterPad = "1";
      preferPerf = "0";
      cellRowOrder = "1";
      cellOffsetX = "0";
      cellOffsetY = "0";
      cellStrideX = "0";
      cellStrideY = "0";
      cellCountX = "3";
      cellCountY = "1";
      cellWidth = "64";
      cellHeight = "64";
      preload = "1";
      allowUnload = "0";
   };
   new t2dAnimationDatablock(animHammer) {
      canSaveDynamicFields = "1";
      imageMap = "imageHammer";
      animationFrames = "0 1 2";
      animationTime = "0.2";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleWhackedLilac) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleLilac";
      animationFrames = "3 5 6 6 5 7 8";
      animationTime = "0.35";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleWhackedRed) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleRed";
      animationFrames = "3 5 6 6 5 7 8";
      animationTime = "0.35";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animMoleWhackedGreen) {
      canSaveDynamicFields = "1";
      imageMap = "imageMoleGreen";
      animationFrames = "3 6 6 5 7 8";
      animationTime = "0.35";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
   new t2dAnimationDatablock(animHammerIdle) {
      canSaveDynamicFields = "1";
      imageMap = "imageHammer";
      animationFrames = "2 2";
      animationTime = "1";
      animationCycle = "0";
      randomStart = "0";
      startFrame = "0";
   };
