
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:67 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
